project:
  type: website
  output-dir: docs
website:
  title: "Thoughts"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mdhvvr/mdhvvr
      - icon: twitter
        href: https://twitter.com/Mdhvvr
format:
  html:
    theme: quartz
    css: styles.css



